application: ncl-ost-blog
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/login_required
  script: do_openid_login.app
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /.*
  script: mainpage.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest